# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Kernel
CONFIG_MAIN_STACK_SIZE=10240

# Peripherals
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_SPI=y
CONFIG_I2C=y

# Serial
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=n

# Subsystems
CONFIG_MODBUS=y
CONFIG_SENSOR=y
CONFIG_SHELL=y

# Modbus
CONFIG_CRC=y
CONFIG_MODBUS_BUFFER_SIZE=256
CONFIG_MODBUS_ROLE_CLIENT=y
CONFIG_MODBUS_FP_EXTENSIONS=y
CONFIG_MODBUS_NONCOMPLIANT_SERIAL_MODE=y
CONFIG_MODBUS_RAW_ADU=y

# SD Card
CONFIG_DISK_DRIVER_SDMMC=y

# File System
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_LFN_MODE_STACK=y
CONFIG_FS_FATFS_MAX_LFN=50

# RTC
CONFIG_MFD_DS3231=y
CONFIG_RTC=y
CONFIG_RTC_DS3231=y

# Sensors
CONFIG_SENSOR_DS3231=y
CONFIG_PZEM004T=y
CONFIG_PZEM004T_ENABLE_RESET_ENERGY=y

# Shell
CONFIG_LOG_CMDS=y
CONFIG_THREAD_NAME=y


# Build System
CONFIG_NO_OPTIMIZATIONS=y
CONFIG_PICOLIBC=y
CONFIG_PICOLIBC_IO_FLOAT=y

# Debugging
CONFIG_KERNEL_SHELL=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y

# Smart Meter
CONFIG_DATE_SHELL=y
CONFIG_BOOT_BANNER_STRING="Starting Switches Smart Meter"
CONFIG_SHELL_PROMPT_UART="switches:~$ "